# https://www.howtocreole.com/2015/04/count-numbers-haitian-creole-0-100.html?m=1

IRREG_ORDINAL_MAP = {
    "en": "premye",
    "de": "dezyèm",
    "twa": "twazyèm",
    "kat": "katriyèm",
    "sis": "sizyèm",
    "nèf": "nevyèm",
    "dis": "dizyèm",
    "ven": "ventyèm",
    "yen": "yinyèm",
}

# Scale / magnitude units mapped to their magnitude order.
SCALES = {
    "san": 1,
    "mil": 2,
    "milyon": 3,
    "milya": 4,
    "bilyon": 5,
    "bilya": 6,
    "trilyon": 7,
    "trilya": 8,
}

# Don't alter the order, it does matter especially for num_to_text.py
TEXT_TO_NUM = {
    "trilya": 10**21,
    "trilyon": 10**18,
    "bilya": 10**15,
    "bilyon": 10**12,
    "milya": 10**9,
    "milyon": 10**6,
    "mil": 1000,
    "san": 100,

    "katrevendisnèf": 99,
    "katrevendizuit": 98,
    "katrevensèt": 97,
    "katrevensèz": 96,
    "katrevenkinz": 95,
    "katrevenkatòz": 94,
    "katreventrèz": 93,
    "katrevendouz": 92,
    "katrevenonz": 91,
    "katrevendis": 90,

    "katreven-nèf": 89,
    "katreven-uit": 88,
    "katreven-sèt": 87,
    "katreven-sis": 86,
    "katreven-senk": 85,
    "katreven-kat": 84,
    "katreven-trèz": 83,
    "katreven-de": 82,
    "katreven-en": 81,
    "katreven": 80,

    "swasanndisnèf": 79,
    "swasanndizuit": 78,
    "swasanndisèt": 77,
    "swasannsèz": 76,
    "swasannkinz": 75,
    "swasannkatòz": 74,
    "swasanntrèz": 73,
    "swasanndouz": 72,
    "swasantonz": 71,
    "swasanndis": 70,

    "swasantnèf": 69,
    "swasanntuit": 68,
    "swasantsèt": 67,
    "swasannsis": 66,
    "swasannsenk": 65,
    "swasannkat": 64,
    "swasanntwa": 63,
    "swasanndè": 62,
    "swasanteyen": 61,
    "swasant": 60,

    "senkantnèf": 59,
    "senkanntuit": 58,
    "senkannsèt": 57,
    "senkannsis": 56,
    "senkannsenk": 55,
    "senkannkat": 54,
    "senkanntwa": 53,
    "senkannde": 52,
    "senkanteyen": 51,
    "senkant": 50,

    "karannèf": 49,
    "karanntuit": 48,
    "karannsèt": 47,
    "karannsis": 46,
    "karannsenk": 45,
    "karannkat": 44,
    "karanntwa": 43,
    "karannde": 42,
    "karanteyen": 41,
    "karant": 40,

    "trantnèf": 39,
    "tranntuit": 38,
    "trannsèt": 37,
    "trannsis": 36,
    "trannsenk": 35,
    "trannkat": 34,
    "tranntwa": 33,
    "trannde": 32,
    "tranteyen": 31,
    "trent": 30,

    "ventnèf": 29,
    "venntuit": 28,
    "vennsèt": 27,
    "vennsis": 26,
    "vennsenk": 25,
    "vennkat": 24,
    "venntwa": 23,
    "vennde": 22,
    "venteyen": 21,
    "ven": 20,

    "disnèf": 19,
    "dizuit": 18,
    "disèt": 17,
    "sèz": 16,
    "kenz": 15,
    "katòz": 14,
    "trèz": 13,
    "douz": 12,
    "onz": 11,
    "dis": 10,
    "nèf": 9,
    "uit": 8,
    "sèt": 7,
    "sis": 6,
    "senk": 5,
    "kat": 4,
    "twa": 3,
    "de": 2,
    "en": 1,
    "zewo": 0,
}
NUM_TO_TEXT = {num: text for text, num in TEXT_TO_NUM.items()}
