"""Builds a sample Haitian Creole corpus set from the CMU Haitian newswire text.

The source corpus (http://www.speech.cs.cmu.edu/haitian/text/newswire-all.ht)
contains mojibake: a subset of the text was UTF-8 encoded twice, leaving stray
C1 control bytes where Haitian Creole diacritics belong (e.g. ``f\\x8a\\x95t``
for ``fèt``). ftfy reverses that, after which the lines are filtered, deduped,
shuffled with a fixed seed, and truncated.

The generated module embeds the CMU data license notice verbatim, as fetched
from http://www.speech.cs.cmu.edu/haitian/text/COPYING Condition 1 of that
license requires the notice, the conditions, and the disclaimer to be retained
with any distribution deriving from the data.

The output is deterministic: re-running against the same upstream corpus with
the same seed produces the same 1,000 sentences.

Usage:
    python scripts/build_sent_corpus.py src/kreyolib/corpus/sample_sentences.py
"""

import random
import re
import sys
import urllib.request
from pathlib import Path

import ftfy

SOURCE_URL = "http://www.speech.cs.cmu.edu/haitian/text/newswire-all.ht"
LICENSE_URL = "http://www.speech.cs.cmu.edu/haitian/text/COPYING"
TARGET_PATH = Path(__file__).parent.parent / "src/kreyolib/corpus/sample_sentences.py"
SAMPLE_SIZE = 1000
SEED = 42

MIN_LINE_LEN = 15
MAX_LINE_LEN = 150
MIN_ALPHA_RATIO = 0.5

HAITIAN_VOWELS = re.compile(r"[aeiouyàâèéêëîïôöùûü]", re.I)


def fetch_source(url: str = SOURCE_URL) -> str:
    """Downloads and decodes the upstream newswire corpus.

    Returns:
        The corpus as a UTF-8 string.

    Raises:
        urllib.error.URLError: If the corpus cannot be downloaded.
    """
    with urllib.request.urlopen(url, timeout=60) as response:  # noqa: S310
        return response.read().decode("utf-8")


def fetch_license(url: str = LICENSE_URL) -> str:
    """Downloads the CMU data license notice.

    Returns:
        The notice as a UTF-8 string, with trailing newlines stripped.

    Raises:
        urllib.error.URLError: If the notice cannot be downloaded.
    """
    with urllib.request.urlopen(url, timeout=60) as response:  # noqa: S310
        return response.read().decode("utf-8").strip()


def is_usable(line: str) -> bool:
    """Keeps lines that read like Haitian Creole prose.

    Filters out recipe fragments, wire-service boilerplate, and lines that are
    mostly digits or punctuation.
    """
    if not MIN_LINE_LEN <= len(line) <= MAX_LINE_LEN:
        return False
    if sum(c.isalpha() for c in line) < len(line) * MIN_ALPHA_RATIO:
        return False
    return bool(HAITIAN_VOWELS.search(line))


def build_corpus(text: str) -> set[str]:
    # Set comprehension deduplicates instantly on ingestion
    usable_lines = {
        ftfy.fix_text(raw.strip())
        for raw in text.splitlines()
        if is_usable(ftfy.fix_text(raw.strip()))
    }

    # Sort to eliminate hash-seed variance across Python runs
    unique_sorted = sorted(usable_lines)

    random.Random(SEED).shuffle(unique_sorted)
    return set(unique_sorted[:SAMPLE_SIZE])


def render_module(corpus: set[str], license_notice: str) -> str:
    """Renders the corpus set as an importable Python module.

    Args:
        corpus: The sampled sentences.
        license_notice: The CMU data license, reproduced verbatim.
    """
    lines = [
        '"""A sample of Haitian Creole sentences for testing and experimentation.',
        "",
        "Generated by scripts/build_corpus.py. Do not edit by hand.",
        "",
        "Source: CMU Haitian newswire corpus,",
        "http://www.speech.cs.cmu.edu/haitian/text/newswire-all.ht",
        "",
        "The source text was repaired with ftfy, filtered to prose-like lines,",
        f"deduplicated, shuffled with seed {SEED}, and truncated to the first",
        f"{SAMPLE_SIZE:,} sentences.",
        "",
        "The sentences are a modified derivative of the source corpus. The CMU",
        "data license notice is reproduced below, as its condition 1 requires",
        "the notice, the conditions, and the disclaimer to be retained with any",
        f"distribution deriving from the data. Fetched from {LICENSE_URL}",
        "",
        "License Notice:",
        "",
    ]
    # The notice is plain ASCII with no quotes or backslashes, so it can be
    # embedded in the docstring without escaping.
    lines += license_notice.splitlines()
    lines += [
        '"""',
        "",
        "SAMPLE_SENTENCES = {",
    ]
    # Sorted for deterministic file output diffs
    lines += [f"    {value!r}," for value in sorted(corpus)]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    corpus = build_corpus(fetch_source())
    notice = fetch_license()
    TARGET_PATH.write_text(render_module(corpus, notice), encoding="utf-8")
    print(f"Wrote {len(corpus)} sentences to {str(TARGET_PATH)}")
    print(f"Embedded {len(notice.splitlines())} lines of license notice")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
